name: 'Run code on top of an LCG view'
description: 'Spawns appropriate docker image and executes user code in the environment of a specified LCG view'
branding:
  icon: 'play'
  color: 'blue'
inputs:
  container:
    description: 'Which container to use as base to setup a view. By default the container is inferred from `view-path` (default: `auto`)'
    required: false
    default: 'auto'
  coverity-container:
    description: 'Location of container that has Coverity Scan installed (default: `ghcr.io/aidasoft/coverity:latest` but not public)'
    required: false
    default: 'ghcr.io/aidasoft/coverity:latest'
  coverity-cmake-command:
    description: 'CMake command for building your project, assuming in source build'
    required: false
    default: ''
  coverity-project:
    description: 'Coverity project name in URL encoding ( / -> %2F e.g. AIDASoft%2FDD4hep)'
    required: false
    default: ''
  coverity-project-token:
    description: 'Coverity project token to interact with the coverity server'
    required: false
    default: ''
  github-pat:
    description: 'GitHub Personal Access Token for reading the Coverity image as it cannot be public'
    required: false
    default: ''
  platform:
    description: 'LCG view platform you are targeting (e.g. x86_64-centos8-gcc10-opt)'
    required: false
    default: ''
  release:
    description: 'LCG view release you are targeting (e.g. LCG_99)'
    required: false
    default: ''
  release-platform:
    description: 'LCG view release platform string you are targeting (e.g. LCG_99/x86_64-centos8-gcc10-opt'
    required: false
    default: ''
  unpacked:
    description: 'Use image from /cvmfs/unpacked.cern.ch with Singularity, or if false use GitHub Container Registry with Docker'
    required: false
    default: 'false'
  run:
    description: 'They payload code you want to execute on top of the view'
    required: false
    default: ''
  run_local_checkout:
    description: 'Run the local checkout of the action and not the main repo code'
    required: false
    default: 'false'
  setup-script:
    description: 'Initialization/Setup script for a view that sets the environment (e.g. setup.sh)'
    required: false
    default: 'setup.sh'
  view-path:
    description: 'Custom path where the setup script for the view is location'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Run payload
      shell: bash
      run: |
        if [ "${{ inputs.run_local_checkout }}" == "true" ]; then
          echo "WARNING running local checkout of the action !"
          .  setup-lcg-view.sh local
        else
          ${{ github.action_path }}/setup-lcg-view.sh
        fi
      shell: bash
      env:
        THIS: ${{ github.action_path }}
        CONTAINER: ${{ inputs.container }}
        COVERITY_CONTAINER : ${{ inputs.coverity-container }}
        COVERITY_CMAKE_COMMAND : ${{ inputs.coverity-cmake-command }}
        COVERITY_PROJECT: ${{ inputs.coverity-project }}
        COVERITY_PROJECT_TOKEN: ${{ inputs.coverity-project-token }}
        GITHUB_PAT: ${{ inputs.github-pat }}
        GITHUB_ACTOR: ${{ github.actor }}
        LCG_RELEASE: ${{ inputs.release }}
        LCG_RELEASE_PLATFORM: ${{ inputs.release-platform }}
        LCG_PLATFORM: ${{ inputs.platform }}
        UNPACKED: ${{ inputs.unpacked }}
        RUN: ${{ inputs.run }}
        SETUP_SCRIPT: ${{ inputs.setup-script }}
        VIEW_PATH: ${{ inputs.view-path }}
