name: 'Run code on top of a LCG view'
description: 'Spawns appropriate docker image and executes user code in the environment of a specified LCG view'
branding:
  icon: 'blue'
  color: 'play'
inputs:
  platform:
    description: 'LCG view platform you are targeting (e.g. x86_64-centos8-gcc10-opt)'
    required: false
    default: ''
  release:
    description: 'LCG view release you are targeting (e.g. LCG_99)'
    required: false
    default: ''
  release-platform:
    description: 'LCG view release platform string you are targeting (e.g. LCG_99/x86_64-centos8-gcc10-opt'
    required: false
    default: ''
  run:
    description: 'They payload code you want to execute on top of the view'
    required: true
    default: ''
  run_local_checkout:
    description: 'Run the local checkout of the action and not the main repo code'
    required: false
    default: 'false'
  setup-script:
    description: 'Initialization/Setup script for a view that sets the environment (e.g. setup.sh)'
    required: false
    default: 'setup.sh'
  view-path:
    description: 'Custom path where the setup script for the view is location'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - run: |
        if [ "${{ inputs.run_local_checkout }}" == "true" ]; then
          echo "WARNING running local checkout of the action !"
          .  setup-lcg-view.sh local
        else
          ${{ github.action_path }}/setup-lcg-view.sh
        fi
      shell: bash
      env:
        THIS: ${{ github.action_path }}
        LCG_RELEASE: ${{ inputs.release }}
        LCG_RELEASE_PLATFORM: ${{ inputs.release-platform }}
        LCG_PLATFORM: ${{ inputs.platform }}
        RUN: ${{ inputs.run }}
        SETUP_SCRIPT: ${{ inputs.setup-script }}
        VIEW_PATH: ${{ inputs.view-path }}
