name: coverity
on: [push, pull_request]
jobs:
  run-coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cvmfs-contrib/github-action-cvmfs@v5
    - uses: aidasoft/run-lcg-view@main
      with:
        run_local_checkout: 'true'
        coverity-container: 'ghcr.io/aidasoft/coverity:latest'
        coverity-cmake-command: 'cmake -DCMAKE_CXX_STANDARD=20  -DUSE_EXTERNAL_CATCH2=OFF ..'
        coverity-project: 'AIDASoft%2Fpodio'
        coverity-project-token: ${{ secrets.PODIO_COVERITY_TOKEN }}
        github-pat: ${{ secrets.READ_COVERITY_IMAGE }}
        release-platform: "LCG_108/x86_64-el9-gcc13-opt"
        run: |
          git clone https://github.com/AIDASoft/podio.git
          cd podio
