name: dev3
on: [push, pull_request]
jobs:
  run-lcg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cvmfs-contrib/github-action-cvmfs@v5
    - uses: aidasoft/run-lcg-view@main
      with:
        run_local_checkout: 'true'
        release-platform: "dev3/x86_64-centos7-gcc10-opt"
        run: |
          gcc --version
          which gcc
