name: iLCSoft
on: [push, pull_request]
jobs:
  run-lcg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cvmfs-contrib/github-action-cvmfs@v5
    - uses: aidasoft/run-lcg-view@main
      with:
        run_local_checkout: 'true'
        view-path: "/cvmfs/clicdp.cern.ch/iLCSoft/lcg/104/nightly/x86_64-centos7-gcc11-opt"
        setup-script: "init_ilcsoft.sh"
        run: |
          which ddsim
          ddsim --help
