name: key4hep
on: [push, pull_request]
jobs:
  run-lcg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: aidasoft/run-lcg-view@main
      with:
        run_local_checkout: 'true'
        container: "centos7"
        view-path: "/cvmfs/sw.hsf.org/key4hep"
        run: |
          which ddsim
          ddsim --help
