name: macOS example
on: [push, pull_request]
jobs:
  run-lcg:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'
        cvmfs_macos_pkg_location: 'https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.7.5/cvmfs-2.7.5.pkg'
    - uses: aidasoft/run-lcg-view@main
      with:
        run_local_checkout: 'true'
        release-platform: "LCG_99/x86_64-mac1015-clang120-opt"
        run: |
          which ddsim
          ddsim --help
